### ISSUE TITLE
Error: KeyError at "opt/splunk/etc/apps/who_da/bin.stream.py, line 60: u'src_ip'

### ISSUE THREAD

**Issue by unseenfire5** [bluecatlabs/who-da-for-splunk#1]
I'm receiving a weird error when I attempt to test the who command against src_ip field.
It looks like there is some weird artifact code glitch being passed as a variable for self.source?

Here is the log error (view screen shot)

![error](https://user-images.githubusercontent.com/46539954/50924735-6e15af00-141e-11e9-9d5f-caf89d1ee849.PNG)

Here is sample search:
![splunk_command](https://user-images.githubusercontent.com/46539954/50924832-a9b07900-141e-11e9-8fe5-9817005f1e44.PNG)

**Comment by michaelrn** [comment]
The code is missing a check that the source field exists.
@unseenfire5 Does your search work if you change your search to only include events that have a src_ip?
src_ip=* | who source="src_ip" | stats count by src_ip ipnet_name

**Comment by unseenfire5** [comment]
Hello Michael,

I tried your recommendation and received a different error. "string indices must be integers."
I attached some screen shots.
![image](https://user-images.githubusercontent.com/46539954/52069168-3812a900-254c-11e9-91f1-951e341dd723.png)

![image](https://user-images.githubusercontent.com/46539954/52069197-42cd3e00-254c-11e9-9574-ced4aa772810.png)

![image](https://user-images.githubusercontent.com/46539954/52069221-524c8700-254c-11e9-8c3c-e4d4256e92b1.png)

**Comment by unseenfire5** [comment]
I also tried without quotations:
![image](https://user-images.githubusercontent.com/46539954/52069910-b459bc00-254d-11e9-9e48-a4f120668368.png)

**Comment by michaelrn** [comment]
I have made changes to remove exceptions where there is an invalid src_ip. Please try again with the updated code.

**Comment by unseenfire5** [comment]
Hi Michael,

I am getting this error now. 

![image](https://user-images.githubusercontent.com/46539954/52304755-6ab00d80-2961-11e9-880d-9e03ce65795c.png)

**Comment by unseenfire5** [comment]
There was no search time error. This is what I seen in internal logs

**Comment by unseenfire5** [comment]
More screen shots:
![image](https://user-images.githubusercontent.com/46539954/52305395-fe360e00-2962-11e9-8b6f-a4c3c0c1aff2.png)

![image](https://user-images.githubusercontent.com/46539954/52305456-258cdb00-2963-11e9-86d1-2dc40b84bf35.png)

**Comment by unseenfire5** [comment]
This time no error during search time and no errors in internal logs.

**Comment by unseenfire5** [comment]
I confirmed that the code changes done have made the integration work. 
I had to re-validate some of the field properties on the DNS record for validation testing.
